### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [SijiaDavis/Splurty-All-about-yorkies#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by SijiaDavis** [comment]
I added the viewport meta tag, and I believe it looks a lot better on mobile devices now. Let me know if anything else can be improved! Thanks!
